apiVersion: batch/v1
kind: Job
metadata:
  name: simulator
  labels: 
    ddos: simulator
spec:
  template:
    spec:
      hostname: simulator
      containers:
        - name: simulator
          image: ghcr.io/mattereppe/guard-simulator:main
          imagePullPolicy: Always
          env:
            - name: USERS
              value: "4"
            - name: MAXDELAY
              value: "8"
      restartPolicy: OnFailure
